version: '3'
services:
  car-shop-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'

  soap-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8001:8001'
    

  rest-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    
